version: '3'
services:
  socks5:
    image: serjs/go-socks5-proxy
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "1080:1080"
    restart: unless-stopped
